# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_id', models.IntegerField()),
                ('item_key', models.IntegerField()),
                ('item_value', models.CharField(max_length=32)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
