# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-19 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dictionary_dictionarydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
