# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('c_category', models.CharField(max_length=30, verbose_name='\u8bfe\u7a0b\u7c7b\u522b')),
                ('c_credit', models.CharField(max_length=4, verbose_name='\u5b66\u5206')),
                ('c_hours', models.CharField(max_length=8, verbose_name='\u5b66\u65f6')),
                ('c_teacher', models.CharField(max_length=10, verbose_name='\u6559\u5e08')),
                ('c_desc', models.CharField(max_length=100, verbose_name='\u8bfe\u7a0b\u8bf4\u660e')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
            },
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': '\u6570\u636e\u5b57\u5178'},
        ),
        migrations.AlterModelOptions(
            name='dictionarydetail',
            options={'verbose_name': '\u6570\u636e\u5b57\u5178\u660e\u7ec6'},
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u5b66\u9662'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7cfb\u522b'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u5b66\u6821'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='code',
            field=models.CharField(max_length=16, verbose_name='\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.CharField(max_length=256, verbose_name='\u5b57\u5178\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='dictionarydetail',
            name='dictionary_id',
            field=models.IntegerField(verbose_name='\u5b57\u5178\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='dictionarydetail',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u9ed8\u8ba4'),
        ),
        migrations.AlterField(
            model_name='dictionarydetail',
            name='item_key',
            field=models.IntegerField(verbose_name='\u6570\u636e\u9879\u952e'),
        ),
        migrations.AlterField(
            model_name='dictionarydetail',
            name='item_value',
            field=models.CharField(max_length=32, verbose_name='\u6570\u636e\u9879\u503c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num',
            field=models.CharField(blank=True, max_length=32, verbose_name='\u5de5\u53f7'),
        ),
    ]
