# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180522_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_category',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c_desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u8bfe\u7a0b\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c_teacher',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u6559\u5e08'),
        ),
    ]
