# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180522_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='c_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='c_credit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='c_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='c_hours',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='c_teacher',
            new_name='teacher',
        ),
    ]
