# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-09 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180609_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='upper_business',
            new_name='upper',
        ),
    ]
