# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-09 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180609_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='upper',
            new_name='parentID',
        ),
        migrations.AddField(
            model_name='department',
            name='iid',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u7ec4\u7ec7\u7f16\u53f7'),
        ),
    ]
