# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180609_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='CS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('place', models.CharField(max_length=100, unique=True, verbose_name='\u5730\u70b9')),
                ('time', models.DateField(blank=True, null=True, verbose_name='\u65f6\u95f4')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6559\u5e08')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u8bf4\u660e')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u5b89\u6392',
                'verbose_name_plural': '\u8bfe\u7a0b\u5b89\u6392',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u5730\u70b9')),
                ('dep', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u6240\u5c5e\u7ec4\u7ec7')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u8bf4\u660e')),
            ],
            options={
                'verbose_name': '\u6388\u8bfe\u5730\u70b9',
                'verbose_name_plural': '\u6388\u8bfe\u5730\u70b9',
            },
        ),
    ]
